name: Build and Push Microservices

on:
  push:
    branches: [ main ]
    paths:
      - 'api-gateway/**'
      - 'auth-service/**'
      - 'availability-service/**'
      - 'orders-service/**'
      - 'payment-service/**'
      - 'email-service/**'
      - 'shared/**'
  workflow_dispatch: # Allows you to manually trigger a build for all services

jobs:
  # 1. Detect which folders changed
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api-gateway: 
              - 'api-gateway/**'
              - 'shared/**'
            auth-service: 
              - 'auth-service/**'
              - 'shared/**'
            availability-service: 
              - 'availability-service/**'
              - 'shared/**'
            orders-service: 
              - 'orders-service/**'
              - 'shared/**'
            payment-service: 
              - 'payment-service/**'
              - 'shared/**'
            email-service: 
              - 'email-service/**'
              - 'shared/**'

  # 2. Build Services
  build:
    needs: changes
    # Run if there are changes OR if we clicked the manual "Run workflow" button
    if: ${{ github.event_name == 'workflow_dispatch' || needs.changes.outputs.packages != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # If manual: build all 6. If push: build only the detected changes.
        service: ${{ github.event_name == 'workflow_dispatch' && fromJSON('["api-gateway", "auth-service", "availability-service", "orders-service", "payment-service", "email-service"]') || fromJSON(needs.changes.outputs.packages) }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build from root context (.) so Docker can see the /shared folder
          docker build -t $ECR_REGISTRY/${{ matrix.service }}:$IMAGE_TAG \
            -f ./${{ matrix.service }}/Dockerfile .
            
          docker push $ECR_REGISTRY/${{ matrix.service }}:$IMAGE_TAG
