name: Build and Push Microservices

on:
  push:
    branches: [ main ]
    paths:
      - 'api-gateway/**'
      - 'auth-service/**'
      - 'availability-service/**'
      - 'orders-service/**'
      - 'payment-service/**'
      - 'email-service/**'
      - 'shared/**'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api-gateway: 
              - 'api-gateway/**'
              - 'shared/**'
            auth-service: 
              - 'auth-service/**'
              - 'shared/**'
            availability-service: 
              - 'availability-service/**'
              - 'shared/**'
            orders-service: 
              - 'orders-service/**'
              - 'shared/**'
            payment-service: 
              - 'payment-service/**'
              - 'shared/**'
            email-service: 
              - 'email-service/**'
              - 'shared/**'

  build:
    needs: changes
    if: ${{ needs.changes.outputs.packages != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJSON(needs.changes.outputs.packages) }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::996549485813:role/github-actions-ecr-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/${{ matrix.service }}:$IMAGE_TAG \
            -f ./${{ matrix.service }}/Dockerfile .
            
          docker push $ECR_REGISTRY/${{ matrix.service }}:$IMAGE_TAG
